# Teacher-Student Comparison Dashboard

This notebook focuses on the teacher-student pipeline:

- teacher dataset size and chronic coverage,
- teacher action-0 / non-idle balance,
- heuristic overwrite and force-noop rates,
- behavior-cloning training curves stored inside student checkpoints,
- student predicted non-idle rate vs teacher target non-idle rate,
- standalone full-test JSON summaries for student checkpoints.

It focuses on teacher-dataset summaries, student BC checkpoints, and full-test evaluation outputs.

In [28]:
from pathlib import Path
import importlib
import sys

for candidate in [Path.cwd(), *Path.cwd().parents]:
    helpers = candidate / "helpers"
    repo_helpers = candidate / "Topology_Task" / "analysis" / "metrics" / "helpers"
    if helpers.exists() and (helpers / "comparison_dashboard.py").exists():
        sys.path.insert(0, str(helpers))
        break
    if repo_helpers.exists() and (repo_helpers / "comparison_dashboard.py").exists():
        sys.path.insert(0, str(repo_helpers))
        break
else:
    raise FileNotFoundError("Could not locate Topology_Task/analysis/metrics/helpers")

import comparison_dashboard as cd
cd = importlib.reload(cd)
print("comparison_dashboard:", cd.__file__)
print("TASK_DIR:", cd.TASK_DIR)

comparison_dashboard: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/analysis/metrics/helpers/comparison_dashboard.py
TASK_DIR: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task

## Configuration

In [29]:
DATASET_ROOT = cd.TEACHER_DATASET_ROOT
STUDENT_CHECKPOINT_DIR = cd.TEACHER_STUDENT_CHECKPOINT_DIR
SHOW_FIGURES = True
SAVE_FIGURES = True

print("Dataset root:", DATASET_ROOT)
print("Student checkpoint dir:", STUDENT_CHECKPOINT_DIR)

Dataset root: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/teacher_student_datasets
Student checkpoint dir: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/checkpoint/teacher_student

## Teacher Dataset Summaries

In [30]:
dataset_df, dataset_agent_df = cd.load_teacher_dataset_summaries(DATASET_ROOT)
print("datasets:", len(dataset_df))
display(dataset_df.sort_values("dataset") if not dataset_df.empty else dataset_df)
print("agent summaries:")
display(dataset_agent_df.sort_values(["dataset", "agent"]) if not dataset_agent_df.empty else dataset_agent_df)
cd.plot_teacher_dataset_balance(dataset_agent_df, show=SHOW_FIGURES, save=SAVE_FIGURES)

datasets: 3

,dataset,bad,path,metadata_path,status,checkpoint,checkpoint_global_step,split,eval_action_heuristic,eval_action_rho_threshold,n_env_steps,n_agent_examples,n_completed_episodes,n_unique_chronic_fingerprints,n_shards,dataset_family,dataset_seed
0,local_rho090_s0,False,/Users/corentinplumet/Documents/RL_Marl2grid/T...,/Users/corentinplumet/Documents/RL_Marl2grid/T...,complete,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,14640000,train,local_rho_threshold,0.9,5288287,15864861,803,803,106,local_rho090,0.0
1,local_rho090_s1,False,/Users/corentinplumet/Documents/RL_Marl2grid/T...,/Users/corentinplumet/Documents/RL_Marl2grid/T...,complete,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,14480000,train,local_rho_threshold,0.9,6406417,19219251,803,803,129,local_rho090,1.0
2,local_rho090_s2,False,/Users/corentinplumet/Documents/RL_Marl2grid/T...,/Users/corentinplumet/Documents/RL_Marl2grid/T...,complete,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,15080000,train,local_rho_threshold,0.9,5818906,17456718,803,803,117,local_rho090,2.0

agent summaries:

,dataset,agent,n,teacher_action0_frac,teacher_nonidle_frac,policy_nonidle_frac,force_noop_frac,was_overwritten_frac,overwrite_to_action0_frac,obs_nan_or_inf,dataset_family,dataset_seed
0,local_rho090_s0,agent_0,5288287,0.990441,0.009559,0.708490,0.987539,0.698931,0.698931,None,local_rho090,0.0
1,local_rho090_s0,agent_1,5288287,0.897101,0.102899,0.685626,0.872445,0.582727,0.582727,None,local_rho090,0.0
2,local_rho090_s0,agent_2,5288287,0.897456,0.102544,0.790609,0.805782,0.688065,0.688065,None,local_rho090,0.0
3,local_rho090_s1,agent_0,6406417,0.980357,0.019643,0.999533,0.980348,0.979890,0.979890,None,local_rho090,1.0
4,local_rho090_s1,agent_1,6406417,0.999596,0.000404,0.627844,0.985652,0.627440,0.627440,None,local_rho090,1.0
5,local_rho090_s1,agent_2,6406417,0.976092,0.023908,0.586829,0.922090,0.562922,0.562922,None,local_rho090,1.0
6,local_rho090_s2,agent_0,5818906,0.999794,0.000206,0.101792,0.989471,0.101586,0.101586,None,local_rho090,2.0
7,local_rho090_s2,agent_1,5818906,0.988242,0.011758,0.932946,0.987957,0.921188,0.921188,None,local_rho090,2.0
8,local_rho090_s2,agent_2,5818906,0.974817,0.025183,0.756068,0.934108,0.730885,0.730885,None,local_rho090,2.0

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_dataset_teacher_action0_frac.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_dataset_teacher_nonidle_frac.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_dataset_was_overwritten_frac.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_dataset_force_noop_frac.html

[Figure({
     'data': [{'customdata': array([[0.009720909437151988, 0.9803570388877277, 0.9997942912293135, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.6032716505014691, 0.593468951132761, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'BKb1YI7ogz8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_0<br>t' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_0',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': ''}},
               'name': 'agent_0',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'a5DZP7Kv7z8=', 'dtype': 'f8'}},
              {'customdata': array([[0.056185899564204195, 0.8971005166701429, 0.999596342229986, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.748805369036468, 0.7104517525339338, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'RMs/8mXErD8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_1<br>t' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_1',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '/'}},
               'name': 'agent_1',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'eAbuos7F7j8=', 'dtype': 'f8'}},
              {'customdata': array([[0.045037042919486216, 0.8974562084092638, 0.9760922525024518, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.7111686277231112, 0.660623925132965, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'ZT7lZBgPpz8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_2<br>t' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_2',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '\\'}},
               'name': 'agent_2',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': '8XRsE/Bh7j8=', 'dtype': 'f8'}}],
     'layout': {'bargap': 0.18,
                'bargroupgap': 0.04,
                'barmode': 'group',
                'height': 560,
                'legend': {'orientation': 'v',
                           'title': {'text': 'agent'},
                           'x': 1.01,
                           'xanchor': 'left',
                           'y': 1,
                           'yanchor': 'top'},
                'margin': {'b': 120, 'l': 70, 'r': 210, 't': 90},
                'template': '...',
                'title': {'text': 'Teacher dataset action-0 fraction: seed mean by dataset family and agent'},
                'width': 1250,
                'xaxis': {'categoryarray': [local_rho090],
                          'categoryorder': 'array',
                          'tickangle': -30,
                          'title': {'text': 'dataset'}},
                'yaxis': {'range': [0, 1], 'title': {'text': 'teacher_action0_frac'}}}
 }),
 Figure({
     'data': [{'customdata': array([[0.009720909437152012, 0.0002057087706864486, 0.019642961112272272, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.6032716505014691, 0.593468951132761, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'Eqb1YI7ogz8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_0<br>t' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_0',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': ''}},
               'name': 'agent_0',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'c+WbCXAThD8=', 'dtype': 'f8'}},
              {'customdata': array([[0.05618589956420415, 0.0004036577700140344, 0.1028994833298571, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.748805369036468, 0.7104517525339338, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'Pss/8mXErD8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_1<br>t' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_1',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '/'}},
               'name': 'agent_1',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'hZgf0RWjoz8=', 'dtype': 'f8'}},
              {'customdata': array([[0.045037042919486195, 0.023907747497548162, 0.10254379159073629, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.7111686277231112, 0.660623925132965, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'Yj7lZBgPpz8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_2<br>t' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_2',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '\\'}},
               'name': 'agent_2',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': '6LA4yf7gqT8=', 'dtype': 'f8'}}],
     'layout': {'bargap': 0.18,
                'bargroupgap': 0.04,
                'barmode': 'group',
                'height': 560,
                'legend': {'orientation': 'v',
                           'title': {'text': 'agent'},
                           'x': 1.01,
                           'xanchor': 'left',
                           'y': 1,
                           'yanchor': 'top'},
                'margin': {'b': 120, 'l': 70, 'r': 210, 't': 90},
                'template': '...',
                'title': {'text': 'Teacher dataset non-idle fraction: seed mean by dataset family and agent'},
                'width': 1250,
                'xaxis': {'categoryarray': [local_rho090],
                          'categoryorder': 'array',
                          'tickangle': -30,
                          'title': {'text': 'dataset'}},
                'yaxis': {'range': [0, 1], 'title': {'text': 'teacher_nonidle_frac'}}}
 }),
 Figure({
     'data': [{'customdata': array([[0.4485487597620436, 0.1015861057044056, 0.9798896949730247, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.6032716505014691, 0.593468951132761, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 't7d12wW13D8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_0<br>w' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_0',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': ''}},
               'name': 'agent_0',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': '688JmbL94j8=', 'dtype': 'f8'}},
              {'customdata': array([[0.18386728871994368, 0.5827268830152372, 0.92118810649287, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.748805369036468, 0.7104517525339338, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'zpztm/aIxz8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_1<br>w' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_1',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '/'}},
               'name': 'agent_1',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'uJxQUAW85j8=', 'dtype': 'f8'}},
              {'customdata': array([[0.08727941841727238, 0.5629216768124835, 0.7308853244922671, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.7111686277231112, 0.660623925132965, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'WFG3p/FXtj8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_2<br>w' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_2',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '\\'}},
               'name': 'agent_2',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': '79YsydQj5T8=', 'dtype': 'f8'}}],
     'layout': {'bargap': 0.18,
                'bargroupgap': 0.04,
                'barmode': 'group',
                'height': 560,
                'legend': {'orientation': 'v',
                           'title': {'text': 'agent'},
                           'x': 1.01,
                           'xanchor': 'left',
                           'y': 1,
                           'yanchor': 'top'},
                'margin': {'b': 120, 'l': 70, 'r': 210, 't': 90},
                'template': '...',
                'title': {'text': 'Teacher heuristic overwrite fraction: seed mean by dataset family and agent'},
                'width': 1250,
                'xaxis': {'categoryarray': [local_rho090],
                          'categoryorder': 'array',
                          'tickangle': -30,
                          'title': {'text': 'dataset'}},
                'yaxis': {'range': [0, 1], 'title': {'text': 'was_overwritten_frac'}}}
 }),
 Figure({
     'data': [{'customdata': array([[0.004807258600533145, 0.9803482976521822, 0.9894708730472704, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.6032716505014691, 0.593468951132761, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'rzKQp8awcz8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_0<br>f' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_0',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': ''}},
               'name': 'agent_0',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'YEM3HY+L7z8=', 'dtype': 'f8'}},
              {'customdata': array([[0.06603592116280782, 0.8724447065751159, 0.9879573583075582, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.748805369036468, 0.7104517525339338, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': 'DGjB6brnsD8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_1<br>f' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_1',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '/'}},
               'name': 'agent_1',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': '8xA/PaBb7j8=', 'dtype': 'f8'}},
              {'customdata': array([[0.07087515406123748, 0.8057815319024856, 0.9341080608622996, 3,
                                     '[0, 1, 2]',
                                     "['local_rho090_s0', 'local_rho090_s1', 'local_rho090_s2']",
                                     0.7111686277231112, 0.660623925132965, 17513610, 5837870.0]],
                                   dtype=object),
               'error_y': {'array': {'bdata': '+r7KxN8ksj8=', 'dtype': 'f8'}, 'type': 'data', 'visible': True},
               'hovertemplate': ('run=%{x}<br>agent=agent_2<br>f' ... 'tomdata[9]:.0f}<extra></extra>'),
               'legendgroup': 'agent_2',
               'marker': {'color': [#636EFA],
                          'line': {'color': 'rgba(0,0,0,0.35)', 'width': 0.7},
                          'pattern': {'shape': '\\'}},
               'name': 'agent_2',
               'type': 'bar',
               'x': array(['local_rho090'], dtype=object),
               'y': {'bdata': 'FxeXYvpk7D8=', 'dtype': 'f8'}}],
     'layout': {'bargap': 0.18,
                'bargroupgap': 0.04,
                'barmode': 'group',
                'height': 560,
                'legend': {'orientation': 'v',
                           'title': {'text': 'agent'},
                           'x': 1.01,
                           'xanchor': 'left',
                           'y': 1,
                           'yanchor': 'top'},
                'margin': {'b': 120, 'l': 70, 'r': 210, 't': 90},
                'template': '...',
                'title': {'text': 'Teacher force-noop fraction: seed mean by dataset family and agent'},
                'width': 1250,
                'xaxis': {'categoryarray': [local_rho090],
                          'categoryorder': 'array',
                          'tickangle': -30,
                          'title': {'text': 'dataset'}},
                'yaxis': {'range': [0, 1], 'title': {'text': 'force_noop_frac'}}}
 })]

## Teacher Dataset Cross-Seed Comparison

This tells you whether the teacher seeds are teaching the same sparse behavior or if each seed specializes different agents.

In [31]:
if not dataset_agent_df.empty:
    dataset_agent_seed_summary = cd.aggregate_teacher_dataset_agents(dataset_agent_df)
    pivot = dataset_agent_seed_summary.pivot_table(
        index="dataset_family",
        columns="agent",
        values=["teacher_action0_frac", "teacher_nonidle_frac", "was_overwritten_frac", "force_noop_frac"],
        aggfunc="mean",
    )
    display(pivot)

    import plotly.express as px
    fig = px.scatter(
        dataset_agent_seed_summary,
        x="teacher_nonidle_frac",
        y="was_overwritten_frac",
        color="dataset_family",
        symbol="agent",
        hover_data=["teacher_action0_frac", "force_noop_frac", "policy_nonidle_frac", "n_seed_datasets", "seeds", "datasets"],
        labels={
            "teacher_nonidle_frac": "teacher non-idle fraction",
            "was_overwritten_frac": "heuristic overwrite fraction",
        },
        title="Teacher dataset: non-idle target vs heuristic overwrite rate",
    )
    fig.update_layout(template="plotly_white", height=650, width=1050)
    cd.save_fig(fig, "teacher_student_dataset_nonidle_vs_overwrite", save=SAVE_FIGURES)
    if SHOW_FIGURES:
        fig.show()

               force_noop_frac                     teacher_action0_frac  \
agent                  agent_0   agent_1   agent_2              agent_0
dataset_family
local_rho090          0.985786  0.948685  0.887326             0.990197

                                   teacher_nonidle_frac                      \
agent            agent_1   agent_2              agent_0   agent_1   agent_2
dataset_family
local_rho090    0.961646  0.949455             0.009803  0.038354  0.050545

               was_overwritten_frac
agent                       agent_0   agent_1   agent_2
dataset_family
local_rho090               0.593469  0.710452  0.660624

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_student_dataset_nonidle_vs_overwrite.html

## Student BC Checkpoint Metrics

In [32]:
student_ckpt_df, student_epoch_df = cd.load_teacher_student_checkpoints(STUDENT_CHECKPOINT_DIR)
print("student checkpoints:", len(student_ckpt_df))
display(student_ckpt_df.sort_values("checkpoint") if not student_ckpt_df.empty else student_ckpt_df)
print("epoch metrics:")
display(student_epoch_df.sort_values(["checkpoint", "epoch", "phase", "agent"]) if not student_epoch_df.empty else student_epoch_df)
cd.plot_student_bc_metrics(student_epoch_df, show=SHOW_FIGURES, save=SAVE_FIGURES)

student checkpoints: 6

,checkpoint,path,global_step,dataset,teacher_checkpoint,teacher_checkpoint_global_step,epochs,batch_size,balanced_nonidle_frac,nonidle_weight,aux_intervention_loss,aux_weight,soft_distillation_loss,soft_weight,soft_temperature,student_training_objective,dataset_n_env_steps,dataset_n_agent_examples,checkpoint_family,checkpoint_seed,dataset_family,dataset_seed
0,local_bc_bal020_w3_aux025_s0.tar,/Users/corentinplumet/Documents/RL_Marl2grid/T...,12375,local_rho090_s0,a0_hvg_04_eval_local_rho090_s0.tar,14640000,3,4096,0.2,3.0,True,0.25,None,None,None,None,5288287,15864861,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
1,local_bc_bal020_w3_aux025_s1.tar,/Users/corentinplumet/Documents/RL_Marl2grid/T...,14994,local_rho090_s1,a0_hvg_04_eval_local_rho090_s1.tar,14480000,3,4096,0.2,3.0,True,0.25,None,None,None,None,6406417,19219251,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
2,local_bc_bal020_w3_aux025_s2.tar,/Users/corentinplumet/Documents/RL_Marl2grid/T...,13617,local_rho090_s2,a0_hvg_04_eval_local_rho090_s2.tar,15080000,3,4096,0.2,3.0,True,0.25,None,None,None,None,5818906,17456718,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
3,local_bc_s0.tar,/Users/corentinplumet/Documents/RL_Marl2grid/T...,12375,local_rho090_s0,a0_hvg_04_eval_local_rho090_s0.tar,14640000,3,4096,0.5,5.0,True,0.50,None,None,None,None,5288287,15864861,local_bc,0.0,local_rho090,0.0
4,local_bc_s1.tar,/Users/corentinplumet/Documents/RL_Marl2grid/T...,14994,local_rho090_s1,a0_hvg_04_eval_local_rho090_s1.tar,14480000,3,4096,0.5,5.0,True,0.50,None,None,None,None,6406417,19219251,local_bc,1.0,local_rho090,1.0
5,local_bc_s2.tar,/Users/corentinplumet/Documents/RL_Marl2grid/T...,13617,local_rho090_s2,a0_hvg_04_eval_local_rho090_s2.tar,15080000,3,4096,0.5,5.0,True,0.50,None,None,None,None,5818906,17456718,local_bc,2.0,local_rho090,2.0

epoch metrics:

,checkpoint,dataset,epoch,optimizer_steps,phase,agent,n,loss,action_loss,aux_loss,accuracy,teacher_nonidle_frac,pred_nonidle_frac,false_noop_rate,false_intervention_rate,checkpoint_family,checkpoint_seed,dataset_family,dataset_seed
3,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,1,4125,eval,agent_0,195056.0,NaN,NaN,NaN,0.975438,0.009208,0.032478,0.070090,0.023906,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
4,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,1,4125,eval,agent_1,195056.0,NaN,NaN,NaN,0.964087,0.102750,0.127938,0.038217,0.032611,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
5,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,1,4125,eval,agent_2,195056.0,NaN,NaN,NaN,0.965010,0.103468,0.129394,0.037382,0.033089,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
0,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,1,4125,train,agent_0,5632000.0,0.326651,0.300402,0.104997,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
1,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,1,4125,train,agent_1,5632000.0,0.311548,0.281544,0.120015,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
2,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,1,4125,train,agent_2,5632000.0,0.244989,0.217602,0.109548,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
9,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,2,8250,eval,agent_0,195056.0,NaN,NaN,NaN,0.976571,0.009208,0.031622,0.054215,0.022939,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
10,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,2,8250,eval,agent_1,195056.0,NaN,NaN,NaN,0.973572,0.102750,0.117525,0.046669,0.021855,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
11,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,2,8250,eval,agent_2,195056.0,NaN,NaN,NaN,0.975535,0.103468,0.119099,0.038948,0.021776,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
6,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,2,8250,train,agent_0,5632000.0,0.206673,0.189332,0.069363,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
7,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,2,8250,train,agent_1,5632000.0,0.195448,0.175387,0.080246,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
8,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,2,8250,train,agent_2,5632000.0,0.147886,0.131116,0.067079,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
15,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,3,12375,eval,agent_0,195056.0,NaN,NaN,NaN,0.977273,0.009208,0.031006,0.040665,0.022298,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
16,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,3,12375,eval,agent_1,195056.0,NaN,NaN,NaN,0.972526,0.102750,0.121570,0.032704,0.024786,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
17,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,3,12375,eval,agent_2,195056.0,NaN,NaN,NaN,0.978539,0.103468,0.117115,0.034317,0.019043,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
12,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,3,12375,train,agent_0,5632000.0,0.179548,0.163632,0.063664,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
13,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,3,12375,train,agent_1,5632000.0,0.167605,0.149830,0.071100,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
14,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,3,12375,train,agent_2,5632000.0,0.124686,0.110332,0.057416,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,0.0,local_rho090,0.0
21,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,1,4998,eval,agent_0,195056.0,NaN,NaN,NaN,0.986368,0.019143,0.032129,0.010266,0.013615,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
22,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,1,4998,eval,agent_1,195056.0,NaN,NaN,NaN,0.978052,0.000308,0.022240,0.000000,0.021946,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
23,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,1,4998,eval,agent_2,195056.0,NaN,NaN,NaN,0.975479,0.021712,0.045136,0.027803,0.024654,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
18,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,1,4998,train,agent_0,6823936.0,0.163338,0.145819,0.070076,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
19,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,1,4998,train,agent_1,6823936.0,0.287042,0.260609,0.105729,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
20,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,1,4998,train,agent_2,6823936.0,0.179885,0.160062,0.079290,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
27,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,2,9996,eval,agent_0,195056.0,NaN,NaN,NaN,0.989521,0.019143,0.029063,0.009749,0.010449,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
28,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,2,9996,eval,agent_1,195056.0,NaN,NaN,NaN,0.986501,0.000308,0.013796,0.000000,0.013497,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
29,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,2,9996,eval,agent_2,195056.0,NaN,NaN,NaN,0.981159,0.021712,0.039635,0.025870,0.018901,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
24,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,2,9996,train,agent_0,6823936.0,0.078888,0.070625,0.033050,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
25,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,2,9996,train,agent_1,6823936.0,0.156322,0.141458,0.059458,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
26,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,2,9996,train,agent_2,6823936.0,0.109976,0.097449,0.050106,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
33,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,3,14994,eval,agent_0,195056.0,NaN,NaN,NaN,0.991638,0.019143,0.027095,0.006575,0.008365,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
34,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,3,14994,eval,agent_1,195056.0,NaN,NaN,NaN,0.987034,0.000308,0.013268,0.000000,0.012969,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
35,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,3,14994,eval,agent_2,195056.0,NaN,NaN,NaN,0.984410,0.021712,0.035723,0.054018,0.015243,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
30,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,3,14994,train,agent_0,6823936.0,0.066342,0.059204,0.028552,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
31,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,3,14994,train,agent_1,6823936.0,0.127900,0.115415,0.049943,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
32,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,3,14994,train,agent_2,6823936.0,0.093116,0.082268,0.043395,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,1.0,local_rho090,1.0
39,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,1,4539,eval,agent_0,195056.0,NaN,NaN,NaN,0.995022,0.000164,0.005127,0.007000,0.004969,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
40,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,1,4539,eval,agent_1,195056.0,NaN,NaN,NaN,0.976079,0.011351,0.033934,0.069354,0.023587,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
41,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,1,4539,eval,agent_2,195056.0,NaN,NaN,NaN,0.978011,0.023352,0.042629,0.084121,0.021035,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
36,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,1,4539,train,agent_0,6197248.0,0.156492,0.144517,0.047903,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
37,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,1,4539,train,agent_1,6197248.0,0.236748,0.211342,0.101625,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
38,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,1,4539,train,agent_2,6197248.0,0.243319,0.217667,0.102608,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
45,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,2,9078,eval,agent_0,195056.0,NaN,NaN,NaN,0.998211,0.000164,0.001923,0.038498,0.001774,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
46,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,2,9078,eval,agent_1,195056.0,NaN,NaN,NaN,0.973802,0.011351,0.036482,0.045223,0.026065,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
47,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,2,9078,eval,agent_2,195056.0,NaN,NaN,NaN,0.973813,0.023352,0.048079,0.021675,0.025944,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
42,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,2,9078,train,agent_0,6197248.0,0.090321,0.083926,0.025580,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
43,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,2,9078,train,agent_1,6197248.0,0.163637,0.145520,0.072468,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
44,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,2,9078,train,agent_2,6197248.0,0.146047,0.130710,0.061346,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
51,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,3,13617,eval,agent_0,195056.0,NaN,NaN,NaN,0.996088,0.000164,0.004060,0.007000,0.003903,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
52,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,3,13617,eval,agent_1,195056.0,NaN,NaN,NaN,0.977806,0.011351,0.032545,0.043176,0.022054,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
53,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,3,13617,eval,agent_2,195056.0,NaN,NaN,NaN,0.979590,0.023352,0.042198,0.024595,0.019944,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
48,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,3,13617,train,agent_0,6197248.0,0.076567,0.070860,0.022830,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
49,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,3,13617,train,agent_1,6197248.0,0.146786,0.130182,0.066416,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
50,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,3,13617,train,agent_2,6197248.0,0.123301,0.110247,0.052216,NaN,NaN,NaN,NaN,NaN,local_bc_bal020_w3_aux025,2.0,local_rho090,2.0
57,local_bc_s0.tar,local_rho090_s0,1,4125,eval,agent_0,195056.0,NaN,NaN,NaN,0.935557,0.009208,0.072897,0.024267,0.064506,local_bc,0.0,local_rho090,0.0
58,local_bc_s0.tar,local_rho090_s0,1,4125,eval,agent_1,195056.0,NaN,NaN,NaN,0.927093,0.102750,0.171315,0.009888,0.077783,local_bc,0.0,local_rho090,0.0
59,local_bc_s0.tar,local_rho090_s0,1,4125,eval,agent_2,195056.0,NaN,NaN,NaN,0.933276,0.103468,0.167060,0.008446,0.072052,local_bc,0.0,local_rho090,0.0
54,local_bc_s0.tar,local_rho090_s0,1,4125,train,agent_0,5632000.0,0.852369,0.779735,0.145267,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
55,local_bc_s0.tar,local_rho090_s0,1,4125,train,agent_1,5632000.0,0.666989,0.585829,0.162320,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
56,local_bc_s0.tar,local_rho090_s0,1,4125,train,agent_2,5632000.0,0.473188,0.400553,0.145271,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
63,local_bc_s0.tar,local_rho090_s0,2,8250,eval,agent_0,195056.0,NaN,NaN,NaN,0.954018,0.009208,0.054656,0.022483,0.046091,local_bc,0.0,local_rho090,0.0
64,local_bc_s0.tar,local_rho090_s0,2,8250,eval,agent_1,195056.0,NaN,NaN,NaN,0.939679,0.102750,0.159339,0.009929,0.064463,local_bc,0.0,local_rho090,0.0
65,local_bc_s0.tar,local_rho090_s0,2,8250,eval,agent_2,195056.0,NaN,NaN,NaN,0.950271,0.103468,0.150547,0.007304,0.053470,local_bc,0.0,local_rho090,0.0
60,local_bc_s0.tar,local_rho090_s0,2,8250,train,agent_0,5632000.0,0.516287,0.469252,0.094071,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
61,local_bc_s0.tar,local_rho090_s0,2,8250,train,agent_1,5632000.0,0.394255,0.338103,0.112303,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
62,local_bc_s0.tar,local_rho090_s0,2,8250,train,agent_2,5632000.0,0.276565,0.232027,0.089076,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
69,local_bc_s0.tar,local_rho090_s0,3,12375,eval,agent_0,195056.0,NaN,NaN,NaN,0.953557,0.009208,0.055102,0.023864,0.046548,local_bc,0.0,local_rho090,0.0
70,local_bc_s0.tar,local_rho090_s0,3,12375,eval,agent_1,195056.0,NaN,NaN,NaN,0.952649,0.102750,0.146327,0.010116,0.049919,local_bc,0.0,local_rho090,0.0
71,local_bc_s0.tar,local_rho090_s0,3,12375,eval,agent_2,195056.0,NaN,NaN,NaN,0.955526,0.103468,0.145733,0.006413,0.047942,local_bc,0.0,local_rho090,0.0
66,local_bc_s0.tar,local_rho090_s0,3,12375,train,agent_0,5632000.0,0.429136,0.387038,0.084197,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
67,local_bc_s0.tar,local_rho090_s0,3,12375,train,agent_1,5632000.0,0.329811,0.280898,0.097827,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
68,local_bc_s0.tar,local_rho090_s0,3,12375,train,agent_2,5632000.0,0.231962,0.193559,0.076807,NaN,NaN,NaN,NaN,NaN,local_bc,0.0,local_rho090,0.0
75,local_bc_s1.tar,local_rho090_s1,1,4998,eval,agent_0,195056.0,NaN,NaN,NaN,0.972695,0.019143,0.046187,0.001372,0.027898,local_bc,1.0,local_rho090,1.0
76,local_bc_s1.tar,local_rho090_s1,1,4998,eval,agent_1,195056.0,NaN,NaN,NaN,0.963862,0.000308,0.036431,0.000000,0.036145,local_bc,1.0,local_rho090,1.0
77,local_bc_s1.tar,local_rho090_s1,1,4998,eval,agent_2,195056.0,NaN,NaN,NaN,0.953188,0.021712,0.068032,0.007631,0.048080,local_bc,1.0,local_rho090,1.0
72,local_bc_s1.tar,local_rho090_s1,1,4998,train,agent_0,6823936.0,0.326161,0.286384,0.079554,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
73,local_bc_s1.tar,local_rho090_s1,1,4998,train,agent_1,6823936.0,0.787006,0.709052,0.155908,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
74,local_bc_s1.tar,local_rho090_s1,1,4998,train,agent_2,6823936.0,0.373576,0.321136,0.104880,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
81,local_bc_s1.tar,local_rho090_s1,2,9996,eval,agent_0,195056.0,NaN,NaN,NaN,0.983897,0.019143,0.034893,0.005119,0.016369,local_bc,1.0,local_rho090,1.0
82,local_bc_s1.tar,local_rho090_s1,2,9996,eval,agent_1,195056.0,NaN,NaN,NaN,0.941837,0.000308,0.058470,0.000000,0.058194,local_bc,1.0,local_rho090,1.0
83,local_bc_s1.tar,local_rho090_s1,2,9996,eval,agent_2,195056.0,NaN,NaN,NaN,0.972510,0.021712,0.048545,0.014505,0.028027,local_bc,1.0,local_rho090,1.0
78,local_bc_s1.tar,local_rho090_s1,2,9996,train,agent_0,6823936.0,0.167127,0.144890,0.044473,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
79,local_bc_s1.tar,local_rho090_s1,2,9996,train,agent_1,6823936.0,0.412665,0.370592,0.084147,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
80,local_bc_s1.tar,local_rho090_s1,2,9996,train,agent_2,6823936.0,0.219588,0.187087,0.065002,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
87,local_bc_s1.tar,local_rho090_s1,3,14994,eval,agent_0,195056.0,NaN,NaN,NaN,0.985353,0.019143,0.033437,0.004367,0.014842,local_bc,1.0,local_rho090,1.0
88,local_bc_s1.tar,local_rho090_s1,3,14994,eval,agent_1,195056.0,NaN,NaN,NaN,0.986204,0.000308,0.014099,0.000000,0.013800,local_bc,1.0,local_rho090,1.0
89,local_bc_s1.tar,local_rho090_s1,3,14994,eval,agent_2,195056.0,NaN,NaN,NaN,0.966866,0.021712,0.054425,0.005416,0.033964,local_bc,1.0,local_rho090,1.0
84,local_bc_s1.tar,local_rho090_s1,3,14994,train,agent_0,6823936.0,0.137859,0.118196,0.039328,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
85,local_bc_s1.tar,local_rho090_s1,3,14994,train,agent_1,6823936.0,0.388992,0.356041,0.065904,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
86,local_bc_s1.tar,local_rho090_s1,3,14994,train,agent_2,6823936.0,0.182682,0.155002,0.055359,NaN,NaN,NaN,NaN,NaN,local_bc,1.0,local_rho090,1.0
93,local_bc_s2.tar,local_rho090_s2,1,4539,eval,agent_0,195056.0,NaN,NaN,NaN,0.995653,0.000164,0.004491,0.027999,0.004339,local_bc,2.0,local_rho090,2.0
94,local_bc_s2.tar,local_rho090_s2,1,4539,eval,agent_1,195056.0,NaN,NaN,NaN,0.942868,0.011351,0.067898,0.019638,0.057735,local_bc,2.0,local_rho090,2.0
95,local_bc_s2.tar,local_rho090_s2,1,4539,eval,agent_2,195056.0,NaN,NaN,NaN,0.953593,0.023352,0.068503,0.016247,0.046872,local_bc,2.0,local_rho090,2.0
90,local_bc_s2.tar,local_rho090_s2,1,4539,train,agent_0,6197248.0,0.487007,0.455954,0.062106,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
91,local_bc_s2.tar,local_rho090_s2,1,4539,train,agent_1,6197248.0,0.498748,0.430020,0.137456,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
92,local_bc_s2.tar,local_rho090_s2,1,4539,train,agent_2,6197248.0,0.518783,0.450184,0.137199,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
99,local_bc_s2.tar,local_rho090_s2,2,9078,eval,agent_0,195056.0,NaN,NaN,NaN,0.989090,0.000164,0.011069,0.000000,0.010908,local_bc,2.0,local_rho090,2.0
100,local_bc_s2.tar,local_rho090_s2,2,9078,eval,agent_1,195056.0,NaN,NaN,NaN,0.944247,0.011351,0.066555,0.021752,0.056376,local_bc,2.0,local_rho090,2.0
101,local_bc_s2.tar,local_rho090_s2,2,9078,eval,agent_2,195056.0,NaN,NaN,NaN,0.954311,0.023352,0.068191,0.007456,0.046309,local_bc,2.0,local_rho090,2.0
96,local_bc_s2.tar,local_rho090_s2,2,9078,train,agent_0,6197248.0,0.300668,0.285743,0.029849,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
97,local_bc_s2.tar,local_rho090_s2,2,9078,train,agent_1,6197248.0,0.348393,0.295723,0.105340,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
98,local_bc_s2.tar,local_rho090_s2,2,9078,train,agent_2,6197248.0,0.322760,0.279930,0.085660,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
105,local_bc_s2.tar,local_rho090_s2,3,13617,eval,agent_0,195056.0,NaN,NaN,NaN,0.996842,0.000164,0.003286,0.038498,0.003139,local_bc,2.0,local_rho090,2.0
106,local_bc_s2.tar,local_rho090_s2,3,13617,eval,agent_1,195056.0,NaN,NaN,NaN,0.949635,0.011351,0.061193,0.022126,0.050924,local_bc,2.0,local_rho090,2.0
107,local_bc_s2.tar,local_rho090_s2,3,13617,eval,agent_2,195056.0,NaN,NaN,NaN,0.958222,0.023352,0.064223,0.006892,0.042249,local_bc,2.0,local_rho090,2.0
102,local_bc_s2.tar,local_rho090_s2,3,13617,train,agent_0,6197248.0,0.217881,0.204556,0.026650,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
103,local_bc_s2.tar,local_rho090_s2,3,13617,train,agent_1,6197248.0,0.309058,0.260643,0.096830,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0
104,local_bc_s2.tar,local_rho090_s2,3,13617,train,agent_2,6197248.0,0.273335,0.236994,0.072682,NaN,NaN,NaN,NaN,NaN,local_bc,2.0,local_rho090,2.0

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/student_bc_eval_accuracy.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/student_bc_eval_pred_nonidle_frac.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/student_bc_eval_false_noop_rate.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/student_bc_eval_false_intervention_rate.html

[Figure({
     'data': [{'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s0.tar',
               'line': {'color': '#636efa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s0.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': 'gVenYck27z8yK6l4EUDvPy+whm7SRe8/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s0.tar',
               'line': {'color': '#636efa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s0.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': 'ODbWec3Z7j+O3GfSfyfvPy+W8IHuHu8/', 'dtype': 'f8'},
               'yaxis': 'y2'},
              {'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s0.tar',
               'line': {'color': '#636efa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s0.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x',
               'y': {'bdata': 'OHDgwFzh7j/NnAuplTfvPx6YzA8yUO8/', 'dtype': 'f8'},
               'yaxis': 'y'},
              {'customdata': array([['local_rho090_s1', 4998],
                                    ['local_rho090_s1', 9996],
                                    ['local_rho090_s1', 14994]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s1.tar',
               'line': {'color': '#EF553B', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s1.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': 'RWEYqVOQ7z+TiifbJ6rvP9Yavj2Au+8/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s1', 4998],
                                    ['local_rho090_s1', 9996],
                                    ['local_rho090_s1', 14994]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s1.tar',
               'line': {'color': '#EF553B', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s1.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': 'xb1tqjRM7z/yAE0za5HvP9bAP1zJle8/', 'dtype': 'f8'},
               'yaxis': 'y2'},
              {'customdata': array([['local_rho090_s1', 4998],
                                    ['local_rho090_s1', 9996],
                                    ['local_rho090_s1', 14994]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s1.tar',
               'line': {'color': '#EF553B', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s1.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x',
               'y': {'bdata': 'VMXVZB837z/8phAZqGXvP1x3tJJIgO8/', 'dtype': 'f8'},
               'yaxis': 'y'},
              {'customdata': array([['local_rho090_s2', 4539],
                                    ['local_rho090_s2', 9078],
                                    ['local_rho090_s2', 13617]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s2.tar',
               'line': {'color': '#00cc96', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s2.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': 'zGevQTjX7z/BT5a2V/HvP5TnlJP03+8/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s2', 4539],
                                    ['local_rho090_s2', 9078],
                                    ['local_rho090_s2', 13617]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s2.tar',
               'line': {'color': '#00cc96', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s2.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': 'yXDbUgk87z9X7hakYynvP72Ui5cwSu8/', 'dtype': 'f8'},
               'yaxis': 'y2'},
              {'customdata': array([['local_rho090_s2', 4539],
                                    ['local_rho090_s2', 9078],
                                    ['local_rho090_s2', 13617]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s2.tar',
               'line': {'color': '#00cc96', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s2.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x',
               'y': {'bdata': 'kzs1p95L7z/K/MYkeSnvP00GrCDOWO8/', 'dtype': 'f8'},
               'yaxis': 'y'},
              {'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s0.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s0.tar',
               'line': {'color': '#ab63fa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s0.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': 'mQS7KhXw7T/O5JB0UYfuP/0ILNGJg+4/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s0.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s0.tar',
               'line': {'color': '#ab63fa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s0.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': '0SK6YL6q7T92bE1n2RHuP/HQnssafO4/', 'dtype': 'f8'},
               'yaxis': 'y2'},
              {'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s0.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s0.tar',
               'line': {'color': '#ab63fa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s0.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x',
               'y': {'bdata': 'MVKKu2Td7T/Vi+MUnmjuP5lGYmiqk+4/', 'dtype': 'f8'},
               'yaxis': 'y'},
              {'customdata': array([['local_rho090_s1', 4998],
                                    ['local_rho090_s1', 9996],
                                    ['local_rho090_s1', 14994]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s1.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s1.tar',
               'line': {'color': '#FFA15A', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s1.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': 'sKgBT1Eg7z9GsTprFXzvP+8RFtsCiO8/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s1', 4998],
                                    ['local_rho090_s1', 9996],
                                    ['local_rho090_s1', 14994]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s1.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s1.tar',
               'line': {'color': '#FFA15A', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s1.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': 'ZVSTaPTX7j/MIhnNhyPuP9radpz7ju8/', 'dtype': 'f8'},
               'yaxis': 'y2'},
              {'customdata': array([['local_rho090_s1', 4998],
                                    ['local_rho090_s1', 9996],
                                    ['local_rho090_s1', 14994]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s1.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s1.tar',
               'line': {'color': '#FFA15A', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s1.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x',
               'y': {'bdata': '9nmwtIOA7j97R8xAzh7vP6bYbc+Q8O4/', 'dtype': 'f8'},
               'yaxis': 'y'},
              {'customdata': array([['local_rho090_s2', 4539],
                                    ['local_rho090_s2', 9078],
                                    ['local_rho090_s2', 13617]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s2.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s2.tar',
               'line': {'color': '#19d3f3', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s2.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': '0kUdsmLc7z8G0SK6oKbvPzHedQ0h5u8/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s2', 4539],
                                    ['local_rho090_s2', 9078],
                                    ['local_rho090_s2', 13617]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s2.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s2.tar',
               'line': {'color': '#19d3f3', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s2.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': 'jD1T3Pgr7j+vGScGRTfuP7eU6uNoY+4/', 'dtype': 'f8'},
               'yaxis': 'y2'},
              {'customdata': array([['local_rho090_s2', 4539],
                                    ['local_rho090_s2', 9078],
                                    ['local_rho090_s2', 13617]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_s2.tar<br>' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_s2.tar',
               'line': {'color': '#19d3f3', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_s2.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x',
               'y': {'bdata': 'klXLE9WD7j/IQC1LtonuPx/IerfBqe4/', 'dtype': 'f8'},
               'yaxis': 'y'}],
     'layout': {'annotations': [{'font': {},
                                 'showarrow': False,
                                 'text': 'agent=agent_2',
                                 'textangle': 90,
                                 'x': 0.98,
                                 'xanchor': 'left',
                                 'xref': 'paper',
                                 'y': 0.15666666666666665,
                                 'yanchor': 'middle',
                                 'yref': 'paper'},
                                {'font': {},
                                 'showarrow': False,
                                 'text': 'agent=agent_1',
                                 'textangle': 90,
                                 'x': 0.98,
                                 'xanchor': 'left',
                                 'xref': 'paper',
                                 'y': 0.4999999999999999,
                                 'yanchor': 'middle',
                                 'yref': 'paper'},
                                {'font': {},
                                 'showarrow': False,
                                 'text': 'agent=agent_0',
                                 'textangle': 90,
                                 'x': 0.98,
                                 'xanchor': 'left',
                                 'xref': 'paper',
                                 'y': 0.8433333333333332,
                                 'yanchor': 'middle',
                                 'yref': 'paper'}],
                'height': 820,
                'legend': {'title': {'text': 'checkpoint'}, 'tracegroupgap': 0},
                'template': '...',
                'title': {'text': 'Student BC eval accuracy'},
                'width': 1400,
                'xaxis': {'anchor': 'y', 'domain': [0.0, 0.98], 'title': {'text': 'epoch'}},
                'xaxis2': {'anchor': 'y2', 'domain': [0.0, 0.98], 'matches': 'x', 'showticklabels': False},
                'xaxis3': {'anchor': 'y3', 'domain': [0.0, 0.98], 'matches': 'x', 'showticklabels': False},
                'yaxis': {'anchor': 'x', 'domain': [0.0, 0.3133333333333333], 'title': {'text': 'accuracy'}},
                'yaxis2': {'anchor': 'x2',
                           'domain': [0.34333333333333327, 0.6566666666666665],
                           'title': {'text': 'accuracy'}},
                'yaxis3': {'anchor': 'x3',
                           'domain': [0.6866666666666665, 0.9999999999999998],
                           'title': {'text': 'accuracy'}}}
 }),
 Figure({
     'data': [{'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s0.tar',
               'line': {'color': '#636efa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s0.tar',
               'orientation': 'v',
               'showlegend': True,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x3',
               'y': {'bdata': 'SG3U5O+goD8oYMPItzCgP0E9hakpwJ8/', 'dtype': 'f8'},
               'yaxis': 'y3'},
              {'customdata': array([['local_rho090_s0', 4125],
                                    ['local_rho090_s0', 8250],
                                    ['local_rho090_s0', 12375]], dtype=object),
               'hovertemplate': ('checkpoint=local_bc_bal020_w3_' ... '{customdata[1]}<extra></extra>'),
               'legendgroup': 'local_bc_bal020_w3_aux025_s0.tar',
               'line': {'color': '#636efa', 'dash': 'solid'},
               'marker': {'symbol': 'circle'},
               'mode': 'lines+markers',
               'name': 'local_bc_bal020_w3_aux025_s0.tar',
               'orientation': 'v',
               'showlegend': False,
               'type': 'scatter',
               'x': {'bdata': 'AQID', 'dtype': 'i1'},
               'xaxis': 'x2',
               'y': {'bdata': 'gdNYhkJgwD8bEF8PIha+PwSblsQ5H78/', 'dtype': 'f8'},

## Student Prediction vs Teacher Target

This is the main sanity check after BC: does the student predict non-idle actions at the same rate as the teacher dataset, and is it missing rare non-idle actions?

In [33]:
if not student_epoch_df.empty and not dataset_agent_df.empty:
    latest_eval = (
        student_epoch_df[student_epoch_df["phase"].eq("eval")]
        .sort_values(["checkpoint", "agent", "epoch"])
        .groupby(["checkpoint", "agent"], dropna=False, observed=True)
        .tail(1)
        .copy()
    )

    checkpoint_meta_cols = [
        "checkpoint",
        "dataset",
        "balanced_nonidle_frac",
        "nonidle_weight",
        "aux_weight",
        "soft_distillation_loss",
        "soft_weight",
        "soft_temperature",
        "student_training_objective",
    ]
    checkpoint_meta_cols = [c for c in checkpoint_meta_cols if c in student_ckpt_df.columns]
    checkpoint_meta = student_ckpt_df[checkpoint_meta_cols].copy()
    if "dataset" in checkpoint_meta.columns:
        checkpoint_meta = checkpoint_meta.rename(columns={"dataset": "dataset_from_checkpoint"})

    latest_eval = latest_eval.merge(checkpoint_meta, on="checkpoint", how="left")
    if "dataset" not in latest_eval.columns:
        latest_eval["dataset"] = latest_eval.get("dataset_from_checkpoint")
    elif "dataset_from_checkpoint" in latest_eval.columns:
        latest_eval["dataset"] = latest_eval["dataset"].fillna(latest_eval["dataset_from_checkpoint"])
    latest_eval = latest_eval.drop(columns=["dataset_from_checkpoint"], errors="ignore")

    target = dataset_agent_df[["dataset", "agent"]].copy()
    if "teacher_nonidle_frac" in dataset_agent_df.columns:
        target["target_teacher_nonidle_frac"] = dataset_agent_df["teacher_nonidle_frac"]
    elif "teacher_action0_frac" in dataset_agent_df.columns:
        target["target_teacher_nonidle_frac"] = 1.0 - dataset_agent_df["teacher_action0_frac"]
    if "teacher_action0_frac" in dataset_agent_df.columns:
        target["target_teacher_action0_frac"] = dataset_agent_df["teacher_action0_frac"]
    if "was_overwritten_frac" in dataset_agent_df.columns:
        target["target_was_overwritten_frac"] = dataset_agent_df["was_overwritten_frac"]

    comparison = latest_eval.merge(target, on=["dataset", "agent"], how="left")
    if "teacher_nonidle_frac" in comparison.columns and "target_teacher_nonidle_frac" in comparison.columns:
        comparison["teacher_nonidle_frac"] = comparison["target_teacher_nonidle_frac"].fillna(comparison["teacher_nonidle_frac"])
    elif "target_teacher_nonidle_frac" in comparison.columns:
        comparison["teacher_nonidle_frac"] = comparison["target_teacher_nonidle_frac"]
    if "target_teacher_action0_frac" in comparison.columns:
        comparison["teacher_action0_frac"] = comparison["target_teacher_action0_frac"]
    if "target_was_overwritten_frac" in comparison.columns:
        comparison["was_overwritten_frac"] = comparison["target_was_overwritten_frac"]

    comparison["pred_minus_teacher_nonidle"] = comparison["pred_nonidle_frac"] - comparison["teacher_nonidle_frac"]
    display_columns = [
        "checkpoint", "dataset", "agent", "epoch", "accuracy", "pred_nonidle_frac",
        "teacher_nonidle_frac", "pred_minus_teacher_nonidle", "false_noop_rate",
        "false_intervention_rate", "balanced_nonidle_frac", "nonidle_weight", "aux_weight",
        "soft_distillation_loss", "soft_weight", "soft_temperature",
    ]
    display(comparison[[c for c in display_columns if c in comparison.columns]].sort_values(["checkpoint", "agent"]))

    import plotly.express as px
    fig = px.scatter(
        comparison,
        x="teacher_nonidle_frac",
        y="pred_nonidle_frac",
        color="checkpoint",
        symbol="agent",
        hover_data=[c for c in ["accuracy", "false_noop_rate", "false_intervention_rate", "pred_minus_teacher_nonidle"] if c in comparison.columns],
        title="Student predicted non-idle rate vs teacher dataset non-idle target",
        labels={"teacher_nonidle_frac": "teacher non-idle fraction", "pred_nonidle_frac": "student predicted non-idle fraction"},
    )
    fig.add_shape(type="line", x0=0, y0=0, x1=1, y1=1, line={"dash": "dash", "color": "black"})
    fig.update_layout(template="plotly_white", height=650, width=1050)
    cd.save_fig(fig, "teacher_student_pred_nonidle_vs_teacher_target", save=SAVE_FIGURES)
    if SHOW_FIGURES:
        fig.show()

    fig2 = cd.plot_agent_seed_mean_bar(
        comparison,
        source_col="checkpoint",
        family_col="checkpoint_family" if "checkpoint_family" in comparison.columns else None,
        seed_col="checkpoint_seed" if "checkpoint_seed" in comparison.columns else None,
        value_col="pred_minus_teacher_nonidle",
        title="Student non-idle bias relative to teacher target: seed mean by checkpoint family and agent",
        y_title="predicted - teacher non-idle fraction",
        extra_mean_cols=[c for c in ["teacher_nonidle_frac", "pred_nonidle_frac"] if c in comparison.columns],
        save_name="teacher_student_nonidle_bias_by_agent",
        save=SAVE_FIGURES,
        show=SHOW_FIGURES,
        height=620,
        width=1250,
        add_zero_line=True,
        x_tickangle=-30,
    )
else:
    print("Need both student checkpoint metrics and dataset summaries for this comparison.")

,checkpoint,dataset,agent,epoch,accuracy,pred_nonidle_frac,teacher_nonidle_frac,pred_minus_teacher_nonidle,false_noop_rate,false_intervention_rate,balanced_nonidle_frac,nonidle_weight,aux_weight,soft_distillation_loss,soft_weight,soft_temperature
0,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,agent_0,3,0.977273,0.031006,0.009559,0.021447,0.040665,0.022298,0.2,3.0,0.25,None,None,None
1,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,agent_1,3,0.972526,0.121570,0.102899,0.018671,0.032704,0.024786,0.2,3.0,0.25,None,None,None
2,local_bc_bal020_w3_aux025_s0.tar,local_rho090_s0,agent_2,3,0.978539,0.117115,0.102544,0.014571,0.034317,0.019043,0.2,3.0,0.25,None,None,None
3,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,agent_0,3,0.991638,0.027095,0.019643,0.007452,0.006575,0.008365,0.2,3.0,0.25,None,None,None
4,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,agent_1,3,0.987034,0.013268,0.000404,0.012864,0.000000,0.012969,0.2,3.0,0.25,None,None,None
5,local_bc_bal020_w3_aux025_s1.tar,local_rho090_s1,agent_2,3,0.984410,0.035723,0.023908,0.011815,0.054018,0.015243,0.2,3.0,0.25,None,None,None
6,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,agent_0,3,0.996088,0.004060,0.000206,0.003855,0.007000,0.003903,0.2,3.0,0.25,None,None,None
7,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,agent_1,3,0.977806,0.032545,0.011758,0.020787,0.043176,0.022054,0.2,3.0,0.25,None,None,None
8,local_bc_bal020_w3_aux025_s2.tar,local_rho090_s2,agent_2,3,0.979590,0.042198,0.025183,0.017016,0.024595,0.019944,0.2,3.0,0.25,None,None,None
9,local_bc_s0.tar,local_rho090_s0,agent_0,3,0.953557,0.055102,0.009559,0.045543,0.023864,0.046548,0.5,5.0,0.50,None,None,None
10,local_bc_s0.tar,local_rho090_s0,agent_1,3,0.952649,0.146327,0.102899,0.043428,0.010116,0.049919,0.5,5.0,0.50,None,None,None
11,local_bc_s0.tar,local_rho090_s0,agent_2,3,0.955526,0.145733,0.102544,0.043189,0.006413,0.047942,0.5,5.0,0.50,None,None,None
12,local_bc_s1.tar,local_rho090_s1,agent_0,3,0.985353,0.033437,0.019643,0.013794,0.004367,0.014842,0.5,5.0,0.50,None,None,None
13,local_bc_s1.tar,local_rho090_s1,agent_1,3,0.986204,0.014099,0.000404,0.013695,0.000000,0.013800,0.5,5.0,0.50,None,None,None
14,local_bc_s1.tar,local_rho090_s1,agent_2,3,0.966866,0.054425,0.023908,0.030518,0.005416,0.033964,0.5,5.0,0.50,None,None,None
15,local_bc_s2.tar,local_rho090_s2,agent_0,3,0.996842,0.003286,0.000206,0.003081,0.038498,0.003139,0.5,5.0,0.50,None,None,None
16,local_bc_s2.tar,local_rho090_s2,agent_1,3,0.949635,0.061193,0.011758,0.049435,0.022126,0.050924,0.5,5.0,0.50,None,None,None
17,local_bc_s2.tar,local_rho090_s2,agent_2,3,0.958222,0.064223,0.025183,0.039040,0.006892,0.042249,0.5,5.0,0.50,None,None,None

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_student_pred_nonidle_vs_teacher_target.html

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/teacher_student_nonidle_bias_by_agent.html

## Standalone Full-Test Eval Of Student Checkpoints

Run full-test evals with `--eval-action-heuristic none`, then this cell will pick up the JSON summaries.

In [34]:
full_test = cd.load_full_test_results()
if not full_test.empty:
    student_full_test = full_test[
        full_test["checkpoint"].astype(str).str.contains("teacher_student", case=False, na=False)
        | full_test["run_like"].astype(str).str.contains("bc|student|teacher", case=False, na=False)
    ].copy()
else:
    student_full_test = full_test

display(student_full_test.sort_values("survival_percent", ascending=False) if not student_full_test.empty else student_full_test)
cd.plot_full_test_results(student_full_test, show=SHOW_FIGURES, save=SAVE_FIGURES)

,path,bad,checkpoint,checkpoint_stem,run_like,checkpoint_global_step,split,eval_episodes,eval_action_heuristic,eval_action_rho_threshold,obs_normalization,survival_frac,survival_percent,intervention_gate,intervention_gate_eval_mode
7,/Users/corentinplumet/Documents/RL_Marl2grid/T...,False,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,local_bc_bal020_w3_aux025_s1,local_bc_bal020_w3_aux025_s1,14994,test,201,none,0.9,checkpoint_stats,0.974119,97.411874,False,final_action_map
10,/Users/corentinplumet/Documents/RL_Marl2grid/T...,False,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,local_bc_s1,local_bc_s1,14994,test,201,none,0.9,checkpoint_stats,0.973778,97.377818,False,final_action_map
8,/Users/corentinplumet/Documents/RL_Marl2grid/T...,False,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,local_bc_bal020_w3_aux025_s2,local_bc_bal020_w3_aux025_s2,13617,test,201,none,0.9,checkpoint_stats,0.968558,96.855813,False,final_action_map
11,/Users/corentinplumet/Documents/RL_Marl2grid/T...,False,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,local_bc_s2,local_bc_s2,13617,test,201,none,0.9,checkpoint_stats,0.937942,93.794174,False,final_action_map
9,/Users/corentinplumet/Documents/RL_Marl2grid/T...,False,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,local_bc_s0,local_bc_s0,12375,test,201,none,0.9,checkpoint_stats,0.852584,85.258356,False,final_action_map
6,/Users/corentinplumet/Documents/RL_Marl2grid/T...,False,/home/plumet/RL_Marl2grid/Topology_Task/checkp...,local_bc_bal020_w3_aux025_s0,local_bc_bal020_w3_aux025_s0,12375,test,201,none,0.9,checkpoint_stats,0.780268,78.026781,False,final_action_map

Saved: /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures/full_test_eval_survival_summary.html

## Export Teacher-Student Tables

In [35]:
out_dir = cd.FIG_DIR
out_dir.mkdir(parents=True, exist_ok=True)
if not dataset_df.empty:
    dataset_df.to_csv(out_dir / "teacher_student_dataset_summary.csv", index=False)
if not dataset_agent_df.empty:
    dataset_agent_df.to_csv(out_dir / "teacher_student_dataset_agent_summary.csv", index=False)
if not student_ckpt_df.empty:
    student_ckpt_df.to_csv(out_dir / "teacher_student_checkpoint_summary.csv", index=False)
if not student_epoch_df.empty:
    student_epoch_df.to_csv(out_dir / "teacher_student_epoch_metrics.csv", index=False)
if not student_full_test.empty:
    student_full_test.to_csv(out_dir / "teacher_student_full_test_results.csv", index=False)
print("Wrote CSV summaries to", out_dir)

Wrote CSV summaries to /Users/corentinplumet/Documents/RL_Marl2grid/Topology_Task/outputs/comparison_dashboard_figures